"""initial tables

Revision ID: 2506e2f43e18
Revises: 
Create Date: 2026-04-23 23:28:54.511270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2506e2f43e18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biscuits',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('client_uuid', sa.UUID(), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('client_chat_history',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('client_uuid', sa.UUID(), nullable=False),
    sa.Column('chat_title', sa.String(length=255), nullable=True),
    sa.Column('chat_description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('client_chat_message',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('chat_history_uuid', sa.UUID(), nullable=False),
    sa.Column('chat_message', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('client_list',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('client_name', sa.String(length=100), nullable=True),
    sa.Column('client_email', sa.String(length=120), nullable=True),
    sa.Column('client_status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('client_email')
    )
    op.create_table('client_sessions',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('client_uuid', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.Text(), nullable=False),
    sa.Column('device_info', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('client_usage_limits',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('client_uuid', sa.UUID(), nullable=False),
    sa.Column('token_counter', sa.Integer(), nullable=True),
    sa.Column('token_limit', sa.Integer(), nullable=True),
    sa.Column('token_reset_time', sa.DateTime(), nullable=True),
    sa.Column('last_reset_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_usage_limits')
    op.drop_table('client_sessions')
    op.drop_table('client_list')
    op.drop_table('client_chat_message')
    op.drop_table('client_chat_history')
    op.drop_table('biscuits')
    # ### end Alembic commands ###
