"""restore role_uuid in client_list

Revision ID: 426b0acd27f7
Revises: c67f1d066eef
Create Date: 2026-04-25 11:06:18.435363

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '426b0acd27f7'
down_revision = 'c67f1d066eef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_password_reset_tokens',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('client_uuid', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('biscuits', schema=None) as batch_op:
        batch_op.alter_column('client_uuid',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.drop_column('password')

    with op.batch_alter_table('client_list', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('client_list_role_uuid_fkey'), type_='foreignkey')
        batch_op.drop_column('role_uuid')

    with op.batch_alter_table('client_sessions', schema=None) as batch_op:
        batch_op.drop_column('expires_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    with op.batch_alter_table('client_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_uuid', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('client_list_role_uuid_fkey'), 'client_roles', ['role_uuid'], ['uuid'])

    with op.batch_alter_table('biscuits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.alter_column('client_uuid',
               existing_type=sa.UUID(),
               nullable=True)

    op.drop_table('client_password_reset_tokens')
    # ### end Alembic commands ###
