"""added role & acl tables

Revision ID: c575c10808c9
Revises: 2506e2f43e18
Create Date: 2026-04-24 17:00:17.043434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c575c10808c9'
down_revision = '2506e2f43e18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_acl',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('acl_title', sa.String(length=100), nullable=False),
    sa.Column('acl_description', sa.Text(), nullable=True),
    sa.Column('acl_doc', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('client_roles',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('role_name', sa.String(length=100), nullable=False),
    sa.Column('role_description', sa.Text(), nullable=True),
    sa.Column('allowed_acl', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('client_role_mapping',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('role_uuid', sa.UUID(), nullable=True),
    sa.Column('acl_uuid', sa.UUID(), nullable=True),
    sa.Column('client_auth_code', sa.String(length=100), nullable=True),
    sa.Column('access_valid_from', sa.DateTime(), nullable=True),
    sa.Column('access_valid_to', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['acl_uuid'], ['client_acl.uuid'], ),
    sa.ForeignKeyConstraint(['role_uuid'], ['client_roles.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('client_list', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_uuid', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'client_roles', ['role_uuid'], ['uuid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_list', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('role_uuid')

    op.drop_table('client_role_mapping')
    op.drop_table('client_roles')
    op.drop_table('client_acl')
    # ### end Alembic commands ###
