"""rename password to password_hash in biscuits table

Revision ID: e8f9g2h3i4j5
Revises: c67f1d066eef
Create Date: 2026-04-25 14:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8f9g2h3i4j5'
down_revision = 'c67f1d066eef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename the column from 'password' to 'password_hash'
    op.alter_column('biscuits', 'password', new_column_name='password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename back from 'password_hash' to 'password'
    op.alter_column('biscuits', 'password_hash', new_column_name='password')
    # ### end Alembic commands ###
